### ISSUE TITLE
Is this what I think it is?

### ISSUE THREAD

**Issue by VietThan** [XinhuaZhang/Stochastic-Completion-Field#1]
Hi Xinhua Zhang,

My name is Viet Than, an undergraduate studying computer science at Vanderbilt University. Right now I am looking into reconstruction/creation of data in volumetric images that have regions missing. The approach I'm learning about is based on a 1997 paper by [William and Jacobs](https://www.cs.unm.edu/~williams/williams95stochastic.pdf) that uses Stochastic Completion Field to approximate contours. My question is: is this what you are doing? I'm seeing lots of similarities but I can't be sure. I stumbled upon your code as I'm looking for a working example of the 1997 paper to be able to understand the math and implementation.

Sincerely, Viet Than

**Comment by XinhuaZhang** [comment]
Yes. Professor Williams is my dissertation advisor. My PhD work is partly based on his work. I have implemented his algorithm in
src/STC/CompletionFieldR2S1.hs
The test code is in
test/STCR2S1/STCR2S1.hs
You may run it using script
script/test/runSTCR2S1.sh

The code is in Haskell and I am using Stack. I don't know if you are familiar with them or not. Maybe I can write you a tutorial. I didn't really put much effort it organizing the code.

**Comment by VietThan** [comment]
Well thank you so much!
I am now learning Haskell, hahaha. Well, I have installed Slack on my Linux/Ubuntu machine and when I tried ```$ stack build```, I got ExitFailure.

I tried `$ stack build` again and again because I notice every time the processes needed running reduce every time until it reduces to this error:

`Specified source-dir "test/Deconvolution" does not exist
Specified source-dir "test/OrientationAnalysisShape" does not exist
hmatrix                    > configure
hmatrix                    > Configuring hmatrix-0.19.0.0...
hmatrix                    > Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: Missing dependencies on foreign
hmatrix                    > libraries:
hmatrix                    > * Missing (or bad) C libraries: blas, lapack
hmatrix                    > This problem can usually be solved by installing the system packages that
hmatrix                    > provide these libraries (you may need the "-dev" versions). If the libraries
hmatrix                    > are already installed but in a non-standard location then you can use the
hmatrix                    > flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
hmatrix                    > the library files do exist, it may contain errors that are caught by the C
hmatrix                    > compiler at the preprocessing stage. In this case you can re-run configure
hmatrix                    > with the verbosity flag -v3 to see the error messages.
hmatrix                    > 
`

I've searched up blas and lapack and tried installing with `sudo apt-get install libblas liblapack` and the packages seem to not exist.

Any pointers?

**Comment by XinhuaZhang** [comment]
I just fixed the missing source-dir problem. You can checkout it now. As for the hmatrix dependencies problem, you may need the "-dev" versions as it's said in the error message.  install libblas-dev and liblapack-dev

**Comment by XinhuaZhang** [comment]
also remove the following part in the package.yaml. I still need it but you don't. It causes error too

  CannyEdgeEndPoint-test:                                                                                                                                      
    main:                CannyEdgeEndPoint.hs                                                                                                                  
    source-dirs:         test/CannyEdgeEndPoint                                                                                                                
    ghc-options:                                                                                                                                               
    - -threaded                                                                                                                                                
    - -rtsopts                                                                                                                                                 
    - -O2                                                                                                                                                      
    - -j4                                                                                                                                                      
    - -main-is CannyEdgeEndPoint                                                                                                                               
    - -fno-liberate-case                                                                                                                                       
    - -funfolding-use-threshold1000                                                                                                                            
    - -funfolding-keeness-factor1000                                                                                                                           
    # - -fllvm                                                                                                                                                 
    # - -optlo-O3                                                                                                                                              
    extra-libraries:                                                                                                                                           
    - stdc++                                                                                                                                                   
    - lapack                                                                                                                                                   
    - gomp                                                                                                                                                     
    - fftw3                                                                                                                                                    
    - fftw3f                                                                                                                                                   
    - fftw3l                                                                                                                                                   
    - m                                                                                                                                                        
    # - opencv_imgcodecs                                                                                                                                       
    # - opencv_core                                                                                                                                            
    # - opencv_features2d                                                                                                                                      
    # - opencv_highgui                                                                                                                                         
    # - opencv_calib3d                                                                                                                                         
    # - opencv_imgcodecs                                                                                                                                       
    # - opencv_photo                                                                                                                                           
    # - opencv_video                                                                                                                                           
    # - opencv_imgproc                                                                                                                                         
    # - opencv_videoio                                                                                                                                         
    dependencies:                                                                                                                                              
    - Stochastic-Completion-Field

**Comment by VietThan** [comment]
Thank you, the errors have been reduced. There still seem to be one that isn't there?

`/home/vietthan/Documents/HaskellStack/stochasticField/FFI.hsc:10:10: fatal error: fftw3.h: No such file or directory`

**Comment by XinhuaZhang** [comment]
I just made a small modification, please checkout again.  You need to install fftw3 and its variations such as fftw3d? I don't remember the exact name

**Comment by VietThan** [comment]
It has been fully built!
