### ISSUE TITLE
Creating documentation?

### ISSUE THREAD

**Issue by VietThan** [XinhuaZhang/Stochastic-Completion-Field#2]
Hi Xinhua,

This might be a strange question but I am going to be working along your code and learn the implementation, I'll be making comments and creating documentation/guides. Would you like me to make pull requests and create these documentations for your repo as well? I promise I will do an alright job :)

Viet

**Comment by XinhuaZhang** [comment]
You are welcome to do so. If you can add some guides about how to install it in Ubuntu, it would be great: )

BTW, why are you interested in this work? Are you working with someone,  say a professor?

**Comment by VietThan** [comment]
I will do just that then. Yes, I thought it would be compicated so one of the first thing would be how to install in ubuntu.

I am working on this with professor Oguz Ipek at Vanderbilt University, she was the one who gave me the paper to read. We are looking at this to see if it can apply on bad medical images.
